modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="payout"
version="1.0.0"
displayName="Payout"
authors="RavenholmZombie"
description='''  
Allows server admins to automatically give players items at definable intervals. This mod is highly-configurable.
'''
logoFile="payout.png"

[[dependencies.payout]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
